name: toybox CI

on:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ master ]

jobs:
  MacOS-13:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: brew install gnu-sed
    - name: Configure
      run: make macos_defconfig
    - name: Build
      run: make
    - name: Test
      run: VERBOSE=all make tests

  build-clang:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: sudo apt-get install build-essential clang
      - name: Build with clang
        run: VERBOSE=all CC=clang make defconfig tests

  build-gcc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: sudo apt-get install build-essential
      - name: Build with gcc
        run: VERBOSE=all CC=gcc make defconfig tests
