name: toybox CI

on:
  schedule:
    - cron:  '0 2 * * *'
  push:
    branches: [ master ] # test

jobs:
  MacOS-13:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: brew install gnu-sed
    - name: Configure
      run: make macos_defconfig
    - name: Build
      run: make
    - name: Test
      run: VERBOSE=all make tests

  Ubuntu-22_04:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup
        run: sudo apt-get install -y clang make build-essential
    
      - name: Configure build and test with Clang and ASAN
        env:
          CC: clang
          CFLAGS: -fsanitize=address -fno-omit-frame-pointer -g
          LDFLAGS: -fsanitize=address
          ASAN_OPTIONS: "verbosity=1:log_path=asan.log:abort_on_error=1"
        run: |
          make clean
          make defconfig
          make
          set +e
          make tests || true
          echo "===== ASAN LOG ====="
          cat asan.log || echo "No ASAN log found"
